name = "remix-boilerplate-cloudflare-workers"
main = "./build/index.js"
compatibility_date = "2022-04-05"
compatibility_flags = ["streams_enable_constructors"]

[site]
  bucket = "./public"

[build]
  command = "yarn build"
